[package]
name = "maestro-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
appium-client = "0.2.2"
chrono = "0.4.39"
colored = "2.2.0"
fantoccini = "0.19.3"
once_cell = "1.20.2"
serde = "1.0.215"
serde_json = "1.0.135"
serde_yaml = "0.9.34"
spinners = "4.1.1"
tokio = "1.42.0"
