name: CI/CD Pipeline for RustPilot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android-sdk@v1

      - name: Create Android Virtual Device
        run: |
          echo "y" | sdkmanager "system-images;android-30;google_apis;x86"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" -d "pixel_xl"

      - name: Start Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86
          profile: pixel_xl
          disable-animations: true
          script: |
            adb devices
            adb logcat -c

      - name: Install Appium
        run: |
          npm install -g appium

      - name: Run RustPilot tests on Android
        run: |
          # Aquí colocas los comandos para ejecutar tus pruebas con RustPilot en Android
          # Por ejemplo:
          cargo run --bin rust_pilot ./showcase-wikipedia-android/wikipedia.android.caps.yaml ./showcase-wikipedia-android/run-test.yml
